name: Deploy BlueOS Extension Image

on:
  # Automatically run when a new commit is added to the repository
  push:
  # Automatically run when someone makes a Pull Request to the repository
  #pull_request:
  # Run manually
  workflow_dispatch:


jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy BlueOS Extension
        uses: BlueOS-community/Deploy-BlueOS-Extension@v1
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: oakd-vins
          author: Willian Galvani
          author-email: williangalvani@gmail.com
          maintainer: Willian Galvani
          maintainer-email: williangalvani@gmail.com
